# Generated by Django 5.2.4 on 2025-08-03 22:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0002_remove_member_message_member_birth_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='application_reason',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='member',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
