# Generated by Django 5.2.4 on 2025-08-03 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0003_member_application_reason_member_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='country_code',
            field=models.CharField(default='+49', max_length=5),
        ),
        migrations.AlterField(
            model_name='member',
            name='phone',
            field=models.CharField(max_length=20),
        ),
    ]
