# Generated by Django 5.2.4 on 2025-08-03 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_member_country_code_alter_member_phone'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='valid_until',
            new_name='membership_expiry',
        ),
        migrations.RenameField(
            model_name='member',
            old_name='joined_on',
            new_name='registration_date',
        ),
    ]
